name: docker-orpheusbetter

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: Save Docker image to local file
      run: docker save -o your-image-name.tar my-image-name:latest
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ./your-image-name.tar
